name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: print password
      env:
        MY_PASSWORD: ${{secrets.PASSWORD}}
      run: echo "password is $MY_PASSWORD"
